name: Workstation

on:
  push:
    branches:
      - main
      - master
    paths:
      - "workstation/**"

  schedule:
    - cron: "0 3 * * *"

  workflow_dispatch: {}

env:
  IMAGE_NAME: ghcr.io/noobping/workstation

jobs:
  build:
    name: Build (${{ matrix.arch }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            runs_on: ubuntu-latest
          - arch: arm64
            runs_on: ubuntu-24.04-arm

    runs-on: ${{ matrix.runs_on }}

    container:
      image: fedora:43
      options: >-
        --privileged
        --security-opt seccomp=unconfined

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build tools
        run: |
          dnf -y update
          dnf -y install git podman buildah skopeo jq ca-certificates
          printf "[storage]\ndriver = \"vfs\"\n" > /etc/containers/storage.conf

      - name: Repository
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | buildah login -u "${{ github.actor }}" --password-stdin ghcr.io

      - name: Build & Push
        working-directory: workstation
        env:
          BUILDAH_ISOLATION: chroot
        run: |
          IMAGE="${IMAGE_NAME}:${{ matrix.arch }}"

          buildah bud \
            --pull-always \
            --isolation=chroot \
            -f Containerfile \
            -t "$IMAGE" \
            --label org.opencontainers.image.source="${{ github.repositoryUrl }}" \
            --build-arg UID=1000 \
            --build-arg GID=1000 \
            .

          buildah push "$IMAGE" "docker://$IMAGE"

  manifest:
    name: Manifest
    needs: build
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      id-token: write

    steps:
      - name: Repository
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        run: |
          docker buildx imagetools create \
            -t "${IMAGE_NAME}:latest" \
            "${IMAGE_NAME}:amd64" \
            "${IMAGE_NAME}:arm64"
